### ISSUE TITLE
Issue writing A3

### ISSUE THREAD

**Issue by jstaerk** [ZUGFeRD/ZUV#11]
Allegedly the 505 ZF1 sample does not validate on validator.zugferd.org

**Comment by jstaerk** [comment]
can't reproduce. ZUV 0.4.5 reports no errors and validator.zugferd.org says "ZUGFeRD-PDF und ZUGFeRD-xml sind valide."

**Comment by omocinteractive** [comment]
The problem was the versionnumber auf download (1...x) in the filename. Sorry!

**Comment by omocinteractive** [comment]
... sorry, but i can't get a valid ZUGFeRD-PDF with your testfiles or with my own-files :( I working on this problem since days.

With your testfiles i get:
"A file's name dictionary, as defined in PDF Reference 3.6.3, shall not contain the EmbeddedFiles key"
and with my files:
"A file specification dictionary, as defined in PDF 3.10.2, shall not contain the EF key."

![checker](https://user-images.githubusercontent.com/20245225/40610333-46223b02-6272-11e8-856f-033329392283.png)
![command](https://user-images.githubusercontent.com/20245225/40610334-463f9e0e-6272-11e8-88e9-0103be9f5098.png)

**Comment by omocinteractive** [comment]
... sorry, but i can't get a valid ZUGFeRD-PDF with your testfiles or with my own-files :( I working on this problem since days.

With your testfiles i get:
"A file's name dictionary, as defined in PDF Reference 3.6.3, shall not contain the EmbeddedFiles key"
and with my files:
"A file specification dictionary, as defined in PDF 3.10.2, shall not contain the EF key."
![checker](https://user-images.githubusercontent.com/20245225/40610468-c4c45378-6272-11e8-9779-ffc4f848de3e.png)
![command](https://user-images.githubusercontent.com/20245225/40610469-c4e11a26-6272-11e8-98da-ff3f43b3a0ff.png)

**Comment by jstaerk** [comment]
I'll have a closer look, the input should be PDF/A-1 but the output should definitely not be PDF/A-1(B) but PDF/A-3

**Comment by omocinteractive** [comment]
![bild 219](https://user-images.githubusercontent.com/20245225/40767568-2c7f3b12-64b3-11e8-8c25-8a7b37d35e1d.png)
... here a screenshot from your samplefile.

**Comment by omocinteractive** [comment]
... and here the output-file.
![bild 221](https://user-images.githubusercontent.com/20245225/40767792-d46f5af0-64b3-11e8-9cd8-43169d73b938.png)

**Comment by jstaerk** [comment]
I opened it as Mustangproject issue https://github.com/ZUGFeRD/mustangproject/issues/57 and I'll close it here
