### ISSUE TITLE
ZUGFeRD:mustang:jar:1.6.1 is missing, no dependency information available

### ISSUE THREAD

**Issue by timwetter** [ZUGFeRD/ZUV#17]
can not build with version 1.6.1.
if I change 1.6.1 to 1.6.0 in pom it works

Downloading from mavencentral: http://repo.maven.apache.org/maven2/org/mustangproject/ZUGFeRD/mustang/1.6.1/mustang-1.6.1.pom
Downloading from sonatype-oss-public: https://oss.sonatype.org/content/groups/public/org/mustangproject/ZUGFeRD/mustang/1.6.1/mustang-1.6.1.pom
Downloading from mustang-mvn-repo: https://raw.github.com/ZUGFeRD/mustangproject/mvn-repo/org/mustangproject/ZUGFeRD/mustang/1.6.1/mustang-1.6.1.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/mustangproject/ZUGFeRD/mustang/1.6.1/mustang-1.6.1.pom
**[WARNING] The POM for org.mustangproject.ZUGFeRD:mustang:jar:1.6.1 is missing, no dependency information available**
Downloading from sonatype-oss-public: https://oss.sonatype.org/content/groups/public/com/sanityinc/jargs/2.0-SNAPSHOT/maven-metadata.xml
Downloading from mavencentral: http://repo.maven.apache.org/maven2/com/sanityinc/jargs/2.0-SNAPSHOT/maven-metadata.xml
Downloading from mustang-mvn-repo: https://raw.github.com/ZUGFeRD/mustangproject/mvn-repo/com/sanityinc/jargs/2.0-SNAPSHOT/maven-metadata.xml
Downloaded from sonatype-oss-public: https://oss.sonatype.org/content/groups/public/com/sanityinc/jargs/2.0-SNAPSHOT/maven-metadata.xml (762 B at 1.2 kB/s)
Downloading from mavencentral: http://repo.maven.apache.org/maven2/org/mustangproject/ZUGFeRD/mustang/1.6.1/mustang-1.6.1.jar
Downloading from sonatype-oss-public: https://oss.sonatype.org/content/groups/public/org/mustangproject/ZUGFeRD/mustang/1.6.1/mustang-1.6.1.jar
Downloading from mustang-mvn-repo: https://raw.github.com/ZUGFeRD/mustangproject/mvn-repo/org/mustangproject/ZUGFeRD/mustang/1.6.1/mustang-1.6.1.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/mustangproject/ZUGFeRD/mustang/1.6.1/mustang-1.6.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.811 s
[INFO] Finished at: 2019-04-04T13:02:55+02:00
[INFO] Final Memory: 12M/363M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ZUV: Could not resolve dependencies for project org.zugferd:ZUV:jar:0.7.0b-SNAPSHOT: Could not find artifact org.mustangproject.ZUGFeRD:mustang:jar:1.6.1 in mavencentral (http://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by jstaerk** [comment]
Hi,
The current development snapshot version of ZUV is based on the development snapshot of mustang 1.6.1. It's unclear if I will release Mustangproject 1.6.1 since 1.7.0 is in the making.

You should be able to pull and build it yourself but for your convenience I uploaded a binary on http://mustangproject.org/files/mustang-1.6.1-SNAPSHOT.jar . 
You can then bypass the repo and install it directly in your maven cache using `mvn install:install-file -Dfile=mustang-1.6.1-SNAPSHOT.jar -DgroupId=org.mustangproject.ZUGFeRD -DartifactId=mustang -Dversion=1.6.1 -Dpackaging=jar -DgeneratePom=true`. Apologies for making it look in the source code as if the version was actually there, I did not consider that it was misleading and install-file seems to be the only way to deal with prereleases.  Which were needed because we were in the middle of https://github.com/ZUGFeRD/ZUV/issues/14 when ZF2 was released.

Please note that temporarily there is also a snapshot of the current ZUV as binary on http://mustangproject.org/files/ZUV-0.7.0b-SNAPSHOT.jar
