### ISSUE TITLE
Rundungsproblem Geschäftregel BR-CO-17

### ISSUE THREAD

**Issue by LarsFiedler** [ZUGFeRD/ZUV#33]
Validierung gegen Schematron Datei FACTUR-X_EXTENDED.scmt die mit der Dokumentation für 2.1 ausgeliefert wurde. 
Verstoss gegen Geschäftregel BR-CO-17 wird gemeldet, der wohl auf eineim Rundungproblem mit xsl/xslt beruht.

Regel in der Schematron:
<assert test="ram:CalculatedAmount = round(ram:BasisAmount * ram:RateApplicablePercent) div 100 +0 or not (ram:RateApplicablePercent)">

BasisAmount Amount: -7.50
RateApplicablePercent: 19

round(-7.50 * 19) div 100 in XSL = -1.42 während es mathematisch korrekt – 1.43 heissen müsste (wie es auch vom ERP berechnet wurde).

[factur-x_fail.txt](https://github.com/ZUGFeRD/ZUV/files/4459781/factur-x_fail.txt)

**Comment by jstaerk** [comment]
It's indeed wrong, the calculation should read `round(../ram:BasisAmount * ../ram:RateApplicablePercent div 100) +0)` not  `round(../ram:BasisAmount * ../ram:RateApplicablePercent) div 100 +0`

**Comment by LarsFiedler** [comment]
I am not sure...
"round(-7.50 * 19) div 100 + 0" equals for me to 1.42
"round(-7.50 * 19 div 100) + 0" equals for me to 1

I only get correct number on:
"format-number(-7.50 * 19 div 100, '#.00')" equals to 1.43

**Comment by jstaerk** [comment]
you are right i ment (round(-7.50 * 19) div 100 )+0... i believe

**Comment by jstaerk** [comment]
I had added a `<xsl:value-of select="round(../ram:BasisAmount * ../ram:RateApplicablePercent div 100) +0"/> should be <xsl:value-of select="../ram:CalculatedAmount"/>` because the test is `../ram:CalculatedAmount = round(../ram:BasisAmount * ../ram:RateApplicablePercent) div 100 +0` and the output was `is -1 should be -1.43`. A improved formula would be `round(../ram:BasisAmount * ../ram:RateApplicablePercent) div 100 +0` but that returns 1.42 instead of 1.43 :-(

**Comment by jstaerk** [comment]
internal reference: AWV 59

**Comment by jstaerk** [comment]
We had another look. We assume you want to reimburse 7.50 minimum order charge using a corrected invoice. We are not sure if a) SpecifiedLogisticsServiceCharge may be negative at all and b) if it is applicable to VAT. And are you sure you want to put a 7% skonto on an invoice where you have to reimburse something?
